### ISSUE TITLE
assert error raised with long text

### ISSUE THREAD

**Issue by drupchen** [nuwainfo/tibetaneditor#1]
I copied the text of [this article](http://tibettimes.net/2017/12/04/165330/) in the editor as raw text to be segmented, and it fails each time with the following error:

```
INFO:root:========================================
INFO:root:Time: 2017-12-06 11:21:51.152338
ERROR:root:Uncaught exception
Traceback (most recent call last):
  File "/home/drupchen/PycharmProjects/tibetaneditor/Editor.pyw", line 206, in segment
    self.wordManager.tag(newWords)
  File "/home/drupchen/PycharmProjects/tibetaneditor/Word.py", line 80, in tag
    assert len(words) == len(tags)
AssertionError
INFO:root:========================================
```

I tried a few things to check if it was not the parameters of pytib that caused the error, but it doesn't seem like.
Please tell me if I can be of any help to fix the bug.

**Comment by bear0330** [comment]
We are investigating this problem. Thanks.

**Comment by kevinhuangtw** [comment]
Hello, we tested your article, but the problem didn't appear (we didn't apply your pull request). So we are unable to reproduce the problem, but we found other bugs during testing and fixed them after that.
And we release a new version 0.71, thanks.
