### ISSUE TITLE
POS tag editing doesn't allow opting out of selecting a tag

### ISSUE THREAD

**Issue by thedirk** [nuwainfo/tibetaneditor#11]
Issue — In “POS view”, if I click on a POS tag, I cannot click off the selection box — I am forced to choose a POS option.

Expected behavior — I can click anywhere on my screen that’s not in the selection box, and the previous tag is retained.

**Comment by kevinhuangtw** [comment]
Hello, now in version 0.10, the select box will act as the expected behavior. Thanks.
