### ISSUE TITLE
run segmentation before switching views

### ISSUE THREAD

**Issue by ngawangtrinley** [nuwainfo/tibetaneditor#12]
Replace the segmentation icon by a refresh icon, update the space view icon, run segmentation before each view change. This will fix view transition bugs such as text disappearing when switching views.

Space View:
![icons8-synchronize-96](https://user-images.githubusercontent.com/17675331/35023726-e1a42602-fb76-11e7-9119-c7a3aa37c30d.png)
Space View:
![insert space icon](https://user-images.githubusercontent.com/17675331/35023918-e07db0f8-fb77-11e7-884a-d54999d521fe.png)

**Comment by kevinhuangtw** [comment]
Hello, in version 0.10, the icons have been changed, and the editor will automatically segment the changed text before changing views. Thanks.
