### ISSUE TITLE
update the add format icon

### ISSUE THREAD

**Issue by ngawangtrinley** [nuwainfo/tibetaneditor#13]
We're using the color icons from icons8.com.

Add Icon:
![icons8-plus-96](https://user-images.githubusercontent.com/17675331/35023720-df5d5cf6-fb76-11e7-9887-024d7c28057d.png)

If possible the icon should appear in the line below format profiles. Instead of being between the lines on top.

![image](https://user-images.githubusercontent.com/17675331/35024348-f1d44d06-fb79-11e7-83ab-f8d8668cf271.png)

**Comment by kevinhuangtw** [comment]
Hello, in version 0.10, the icon will show as mentioned above. Thanks.
