### ISSUE TITLE
level format names

### ISSUE THREAD

**Issue by ngawangtrinley** [nuwainfo/tibetaneditor#14]
![image](https://user-images.githubusercontent.com/17675331/35024601-687daffa-fb7b-11e7-8e81-63dbd81c249e.png)

The editingFinished() signal of the QLineEdit can trigger the name string update

By default should name levels "Level #"  ("Level 1", "Level 2", "Level 3", etc...)

**Comment by kevinhuangtw** [comment]
Hello, in version 0.10, the names will be "Level#" now. Thanks.
