### ISSUE TITLE
improve color and file pickers

### ISSUE THREAD

**Issue by ngawangtrinley** [nuwainfo/tibetaneditor#15]
![image](https://user-images.githubusercontent.com/17675331/35025619-8702536c-fb81-11e7-8443-f5b634254b35.png)

The default colors should be as follow:

Level 1 — Green: #87a840 
Level 2 — Yellow: #ddc328
Level 3 — Red: #b63226
Level 4 — Blue: #278da
Level 5 — Dark Purple: #363d5c
Level # — Red

**Comment by kevinhuangtw** [comment]
Hello, in version 0.10, the names can be edited by clicking on the name label, and they have default colors, too. Thank you.
