### ISSUE TITLE
Use insertPlainText() for Copy/Paste

### ISSUE THREAD

**Issue by thedirk** [nuwainfo/tibetaneditor#16]
Issue: Copy / Paste copies fonts & styles — this causes a fatal error when trying to re-segment, and can mess up the color of list highlighting...

Expected behavior: Paste copies only the "plain text" of the original, and puts it in the format of the Editor

**Comment by thedirk** [comment]
![screenshot 48](https://user-images.githubusercontent.com/20481710/35025511-9745ac6e-fb78-11e7-8981-b1dab32adc88.png)

un-spacing converts old plain text into the new, pasted format! 

![screenshot 49](https://user-images.githubusercontent.com/20481710/35025588-e50dfb68-fb78-11e7-9205-008113b2bcbd.png)

top: plain text, as entered in the editor itself 
below: copy/paste brings a new font and new color into the mix

![screenshot 50](https://user-images.githubusercontent.com/20481710/35025587-e4e09984-fb78-11e7-894f-6a50842bdbb9.png)

after copying & pasting colored text with a different font, trying to re-segment (scissors icon) creates a fatal error

**Comment by kevinhuangtw** [comment]
Now the editor will accept plain text (discard format) when pasting sentences.
