### ISSUE TITLE
editor quits unexpectedly 

### ISSUE THREAD

**Issue by Tendol** [nuwainfo/tibetaneditor#19]
When trying to access the file system in Windows 10-64 bit, the editor closes abruptly. 

It crashes when I try to open/save/access files from the computer. 

note: the windows I am currently using is pirated. 

![error](https://user-images.githubusercontent.com/32597613/60257371-f0bcf880-98f0-11e9-8863-15e5f84e98a1.gif)

**Comment by bear0330** [comment]
That's wired, may be you can attach the log file under edit folder or stack trace to us. Thanks.

**Comment by Tendol** [comment]
It looks like there was a problem with my windows installation.
