### ISSUE TITLE
improvement

### ISSUE THREAD

**Issue by drupchen** [nuwainfo/tibetaneditor#3]
This is not actually an issue, but a request to include new features.

I started with your latest version to create [this branchh of my fork](https://github.com/drupchen/tibetaneditor/tree/add-support-for-affixed-POS) (my master is equal to your repo) and added features documented just above [this line](https://github.com/drupchen/tibetaneditor/blob/add-support-for-affixed-POS/README.md#release-note).

My main concern is to separate the NLP treatment of the input string from the logic of the editor. To that end, I have externalized the [Tokenization](https://github.com/drupchen/tibetaneditor/blob/add-support-for-affixed-POS/Tokenizer.py) (formerly segmentation) and what I now call the [ProcessingPipeline](https://github.com/drupchen/tibetaneditor/blob/add-support-for-affixed-POS/ProcessingPipeline.py) that includes the POS tagging amongst other treatments.
I have also created a [new api](https://github.com/drupchen/tibetaneditor/blob/add-support-for-affixed-POS/try-new-RDR-api.py) to RDR and kept all your modifications to RDR. Now, [this tagger](https://github.com/drupchen/tibetaneditor/blob/add-support-for-affixed-POS/RDRPOSTagger/RDRPOSTagger4Local.py) allows to retrain the models in the editor while keeping all your modifications. ([_Word.py](https://github.com/drupchen/tibetaneditor/blob/add-support-for-affixed-POS/_Word.py) uses RDR the way you set it while adding some of my improvements)

The idea is that Word.py calls the tokenizer to create the list of Word objects and that the attributes of the objects in this list is modified (never deleting nor adding elements) by the processing pipeline where we currently call the tag() method.
NT will want to add many more NLP treatments and the best way to do so is that we can do it in these two classes, so the code in Word.py remains clean and we are able to do everything necessary while keeping things simple.

NT tells me the support of the highlight is broken with my modifications. It is true I never looked into it.

Ideally, I would like that you test my changes, copy the code in your repo, modify it in any way you deem necessary and in the end, I would simply delete my fork. I think it will be easier to do it this way, without PR. Later, I would like to be able to have a branch dedicated to the improvement of NLP in your repo, if you agree. Once we pass the sanity check of always returning the same amount of Word objects in the list `words`, there should be no interference at all between the features you will be introducing and those we will be introducing. 

Also note that the bugs of my canceled PR are resolved since I started all over again by forking anew version 0.71 and that I have modified pytib.

**Comment by kevinhuangtw** [comment]
Hello, drupchen. We have merged your branch to our repo.
(https://github.com/nuwainfo/tibetaneditor)
We have done some tests, and fixed a little bugs. But there was an error in "add_lemma_and_UD" in "ProcessingPipeline.py" when segmenting words that we coundn't handle, because we don't know much about the usage of lemma or UD. So we temporarily take it away to make the editor executable.

![image](https://user-images.githubusercontent.com/26361571/34473025-7cce50ba-efa8-11e7-89d2-48ef5a2c34ee.png)

Except for this issue, other functions of the editor seem to be no problem to use.

**Comment by drupchen** [comment]
Thank you for merging!
I will soon propose a PR to cleanup the repo and resolve that issue.
