### ISSUE TITLE
Author-entered text gets deleted when "view" is toggled (spacing or POS)

### ISSUE THREAD

**Issue by thedirk** [nuwainfo/tibetaneditor#9]
Issue: Adding text after segmentation causes text to be deleted if you change the "view" — view with spaced / POS tag view (or turning either on / off) —

Expected behavior: In author-entered text remains, even if it hasn’t been “processed” yet...

**Comment by kevinhuangtw** [comment]
Hello, now in version 0.10, the editor will automatically save the change when changing the views. Thanks.
